This tutorial illustrates how to export expression matrices and cell type labels from SingleCellExperiment objects to 5-fold cross-validation .h5 file as input for Matilda.

## Load package
```{r}
library(scran)
library(caret)
library(glue)
source("data_to_h5.R")
```

## Load datasets and process 
```{r}
###########  load rna and adt, then filt them to 99%  ###########
sce_control <- readRDS("../data/Ramaswamy et al. (GSE166489)/rna.rds") ##modify your path here
sel <- names(which(rowSums(logcounts(sce_control) == 0) / ncol(logcounts(sce_control)) < 0.99))
sce_control <- sce_control[sel,]
rna.filt <- as.matrix(logcounts(sce_control))
adt.filt <- readRDS("../data/Ramaswamy et al. (GSE166489)/adt.rds")  ##modify your path here
adt.filt <- as.matrix(logcounts(adt.filt))
cty <- factor(sce_control$celltype)

###########filter the cell type whose number is less than 10###########
rna.filt <- rna.filt[, cty %in% names(table(cty))[table(cty)>10]]
adt.filt <- adt.filt[, cty %in% names(table(cty))[table(cty)>10]]
cty <- cty[cty %in% names(table(cty))[table(cty)>10]]
cty <- as.character(cty)

################## z-score normalization ##################
mean_rna <- colMeans(rna.filt)
sd_rna <- colSds(rna.filt)
mean_rna<-c(rep(mean_rna,dim(rna.filt)[1]))
mean_rna <-t(matrix(mean_rna, nrow=dim(rna.filt)[2]))
sd_rna<-c(rep(sd_rna,dim(rna.filt)[1]))
sd_rna <-t(matrix(sd_rna, nrow=dim(rna.filt)[2]))
rna.filt <- (rna.filt - mean_rna)/sd_rna

mean_adt <- colMeans(adt.filt)
sd_adt <- colSds(adt.filt)
mean_adt<-c(rep(mean_adt,dim(adt.filt)[1]))
mean_adt <-t(matrix(mean_adt, nrow=dim(adt.filt)[2]))
sd_adt<-c(rep(sd_adt,dim(adt.filt)[1]))
sd_adt <-t(matrix(sd_adt, nrow=dim(adt.filt)[2]))
adt.filt <- (adt.filt - mean_adt)/sd_adt
```


##Saving data as h5 files
```{r}
write_h5_scJoint(exprs_list = list(rna = rbind(rna.filt,adt.filt)), 
           h5file_list = c(glue("./../processed_data/{dataset_name}/data.h5"))) #modify your path here
write_csv_scJoint(cellType_list =  list(rna = cty),
          csv_list = c(glue("./../processed_data/{dataset_name}/cty.csv"))) #modify your path here
```

```{r}
sessionInfo()
```
